name: Update Folder List

on:
  push:
    branches:
      - main

jobs:
  update-folder-list:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate folder list
        run: |
          folder_list=$(find . -type d -mindepth 1 -maxdepth 1 | sort | awk -F/ '{printf "<li><a href=\"%s/\">%s</a></li>\n", $2, $2}')
          sed -i '/<ol id="folder-list">/,/<\/ol>/c\<ol id="folder-list">\n'"$folder_list"'\n</ol>' index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update folder list in index.html"
          git push
